### PR TITLE
Fix merge conflict to JMRI/JMRI/master

### PR DESCRIPTION
**Pull request by bobjacobsen**
Fixes a merge conflict due to an added `@Override` on JMRI/JMRI/master in TamsTrafficController; the rest of the changes are due to merging from JMRI/JMRI/master without conflict.

### CODE REVIEW

**Comment by bobjacobsen** [comment]
Added fixes to some JavaDoc issues that came through when the PR was Travis tested in my own repo.

**Comment by bobjacobsen** [comment]
Updated TamsTurnoutManagerTest.  There was a missed "common edit" (The kind we do to all matching files) because the TamsTurnoutManagerTest file wasn't in JMRI/JMRI/master yet.

**Comment by janboen** [comment]
Is this now OK?
Automatic merge failed; fix conflicts and then commit the result.
C:\Users\Jan\git\JMRI2 [master ↕ +0 ~7 -50 !1 | +0 ~2 -0 !1 !]> git add java/src/jmri/jmrix/tams/TamsTrafficController.java
C:\Users\Jan\git\JMRI2 [master ↕ +0 ~8 -50 | +0 ~2 -0 !]> git stash
Saved working directory and index state WIP on master: ae97f0b Merge branch 'bobjacobsen-janboen-master-update-merge'
HEAD is now at ae97f0b Merge branch 'bobjacobsen-janboen-master-update-merge'
C:\Users\Jan\git\JMRI2 [master ↕ +0 ~2 -0 !]>

**Comment by bobjacobsen** [comment]
I don't see any indication that you've pushed that back to this repository. And I don't see why you did that `git stash`

_Please_ do _exactly_ what I put in the prior note.

**Comment by bobjacobsen** [comment]
If that still doesn't fix it (and it might not because the branch is getting really messed up), please do this:

```
git pull https://github.com/bobjacobsen/JMRI.git janboen-master-update-merge
(fix the conflicts you created and do git add / git commit to store them; do not do a git stash)
git push
```

**Pull request merged**
